---
- hosts: localhost
  connection: local
  become: true

  pre-tasks:

    - name: install updates
      apt:
        update_cache: yes
        upgrade: dist
      when: ansible_distribution in ["ubuntu", "debian"]
      changed_when: False

  tasks:
    - include: tasks/packages.yml
    - include: tasks/users.yml
    - include: tasks/appearance.yml
    - include: tasks/configs.yml
    - include: tasks/provisioning.yml


  - name: install packages
    package:
      name:
        - htop
        - neofetch
        - python3-psutil

  - name: copy wallpaper file
    copy:
      src: files/wallpaper.jpg
      dest: /usr/share/backgrounds/ansible-wallpaper.jpg
      owner: root
      group: root

  - name: set wallpaper
    become_user: lee
    dconf:
      key: "/org/gnome/desktop/background/picture-uri"
      value: "'file:///usr/share/backgrounds/ansible-wallpaper.jpg'"

  - name: set wallpaper position
    become_user: lee
    dconf:
      key: "/org/gnome/desktop/background/picture-options"
      value: "'zoom'"

  - name: copy .bashrc file
    copy:
     src: files/bashrc
     dest: /home/lee/.bashrc
     owner: lee
     group: lee

  - name: copy .bashrc file
    copy:
      src: files/bashrc
      dest: /home/lee/.bashrc
      owner: lee
      group: lee

  - name: add ansible user
    user:
      name: sysadm
      system: yes

  - name: setup sudo for ansible user
    copy:
      src: files/sudoer_sysadm
      dest: /etc/sudoers.d/sysadm
      owner: root
      group: root
      mode: 0440

  - name: add ansible-pull cron job
    cron:
      name: ansible auto-provision
      user: sysadm
      minute: "*/6"
      job: ansible-pull -o -U https://github.com/lee-morgan/ansible_setups.git

