- name: add ansible-pull cron job
  cron:
    name: ansible auto-provision
    user: sysadm
    minute: "*/15"
    job: sudo /usr/bin/ansible-pull -o -U https://github.com/lee-morgan/ansible_setups.git
